### ISSUE TITLE
What default value does Darknet used? (cv2.dnn.blobFromImages)

### ISSUE THREAD

**Issue by leekwunfung817** [AlexeyAB/darknet#1521]
`blobFromImage(image, scalefactor, size, mean, swapRB, crop)`

I test a photo with two different environment

same
1. I use the same model
2. I use the same (.cfg) file and structure

different
1. used in Java or Python OpenCV
2. Unknown (scalefactor, mean, swapRB, crop) parameter

### I cannot detect the image using
`blobFromImage(image, (1.0F / 127.5F), (416, 416), Scalar(0), false, false)`
![h_20180512140207_45437358](https://user-images.githubusercontent.com/18736700/44955167-b4dc2100-aee1-11e8-9636-c7054641bfa0.jpg)

### But darknet application result is more accurate:
`darknet.exe detector test ...`
![predictions](https://user-images.githubusercontent.com/18736700/44955181-dccb8480-aee1-11e8-8c99-52b6fbeb5413.jpg)

**Comment by AlexeyAB** [comment]
@leekwunfung817 

* What version of OpenCV do you use?

* Do you use yolov3.cfg?

* The main difference is - there are pros and cons for each of approach: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485
    * blobFromImage() - letter box cropped - OpenCV
    * letterbox_image() - letter box - original Darknet
    * resize_image() - just resize - this repository

**Comment by leekwunfung817** [comment]
Thanks @AlexeyAB 

- opencv 3.4.3
-  yolov3-tiny.cfg
- I am using Java OpenCV Library, (blobFromImage) perhaps is the only function I can call

**Comment by AlexeyAB** [comment]
Try to use `resized` instead of `frame`

`Mat inputBlob = Dnn.blobFromImage(resized, scale, sz, new Scalar(0), false, false);`

**Comment by AlexeyAB** [comment]
* What `-thresh ` do you use for Detection on Darknet? And what probability of license plate and car do you get on the Darknet and OpenCV?

* Try to resize your image to size 416x416 in Paint-software (or any else), and then use it for detection in the OpenCV-dnn and Darknet.

* In the OpenCV-dnn-module is builtin Test for comparison detection on OpenCV-dnn and Darknet - and it is passed for each commit and pull-requrest to the OpenCV: https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_darknet_importer.cpp#L202-L219

**Comment by leekwunfung817** [comment]
I did not fill in the `-thresh` parameter, is there a default value?

my darknet commd is
```
darknet.exe ^
detector test ^
obj.data ^
my-yolov3-tiny.cfg ^
my-yolov3-tiny_41800.weights ^
20180512.jpg
```
MS-DOS



**Darknet Result:**
```
Car: 98%
License Plate: 100%
```
![predictions](https://user-images.githubusercontent.com/18736700/44992079-c9dfaf80-afc8-11e8-8b74-50e6710a8380.jpg)


**Java OpenCV result:**
`
[License Plate]: 99.69442%
`
I have resized in `416 416` and `224 224` , but both cannot detect

**Comment by AlexeyAB** [comment]
> I have resized in 416 416 and 224 224 , but both cannot detect

As I see the attached images have **352x288** size. Try to use square size 416x416.
What is the width= height= in your cfg-file?

----

> How to know the thresh input parameter in Java?

It is 0.5 by default in the OpenCV-dnn, but it doesn't affect, since car probability is 98% that is higher than 0.5 (50%) https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L24

> What default value of thresh used in darknet.exe?

0.25 https://github.com/AlexeyAB/darknet/blob/18d5e4f39c1441f2c21043ac3204b5cb279f8758/src/detector.c#L1215

**Comment by leekwunfung817** [comment]
Help me @AlexeyAB , I have been try in a week, I cannot find any solution to detect the ### Car

This is my cfg file, It seems like cannot use OpenCV to Detect the Big things like **Car**
But, darknet.exe have no problem to detect the **Car**, What happen? Can you explain the reason?

I tried  the use the following framework
1. tensorflow object detection
2. deeplearning4J
3. darkflow
and it does not work what ever I try to train the model in different way

The following is my .cfg file
```
[net]
# Testing
batch=1
subdivisions=1
# Training
# batch=64
# subdivisions=8
width=224
height=224
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
# burn_in=1000
max_batches = 500200
policy=steps
steps=400000,450000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
batch_normalize=1
filters=21
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=21
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=21
activation=linear



[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=2
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=21
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 8

[convolutional]
batch_normalize=1
filters=21
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=21
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=2
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

```

Thank you very much for answer

**Comment by AlexeyAB** [comment]
If you doesn't use thresh in Java code, then the dafualt theshold will be `0.2`, so this is not a problem: https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/region_layer.cpp#L69

So try to resize your image to 224x224 in paint-software and feed it to OpenCV-Yolo and Darknet-Yolo.
Also check that you use the same cfg and weights file for both cases.
Try to test much more images, 10-20 images, can OpenCV-Yolo detect cars?

----

You can compile `yolo_cpp_dll.sln` to get `yolo_cpp_dll.dll` but there is no Java wrappers, you will need to write it by yourself, so using OpenCV-Yolo is better solution.

**Comment by leekwunfung817** [comment]
I have been resized the image to 224x224 and test it by 2000 image.
**OpenCV still cannot detect the Car**

OpenCV-Yolo and Darknet-Yolo have different structure?
Do you understand the response from [https://github.com/opencv/opencv/issues/12413#issuecomment-418489781](url) ?

**Comment by AlexeyAB** [comment]
Try to use 
```java
java.util.List<Mat> result = new  java.util.ArrayList<Mat>(2);
java.util.List<java.lang.String> outBlobNames = new  java.util.ArrayList<java.lang.String>(2);
outBlobNames.add(0, "yolo_16");
outBlobNames.add(1, "yolo_23");
net.forward(result, outBlobNames);

Mat result_1 = result.get(0);
Mat result_2 = result.get(1);

// get results from each of two output layers: result_1 and result_2
```

instead of `Mat detectionMat = net.forward("yolo_23");`


----

I.e. use this function: https://docs.opencv.org/3.4/javadoc/org/opencv/dnn/Net.html
`void forward(java.util.List<Mat> outputBlobs, java.util.List<java.lang.String> outBlobNames)`

----

Do you understand the response from https://github.com/opencv/opencv/issues/12413#issuecomment-418489781 ?

Yes.
There are 3 [yolo]-layers in yolov3.cfg and 2 [yolo]-layers in the yolov2.cfg, and it looks like you get results only from the first [yolo]-layer.


![image](https://user-images.githubusercontent.com/4096485/45117342-fed13b00-b15d-11e8-9d11-fbb6a0e44269.png)

Also there are several functions `net.forward()` https://github.com/opencv/opencv/blob/master/modules/dnn/src/dnn.cpp#L2458
* `Mat Net::forward(const String& outputName) `

* `void Net::forward(OutputArrayOfArrays outputBlobs, const String& outputName)`

* `void Net::forward(OutputArrayOfArrays outputBlobs, const std::vector<String>& outBlobNames)`

* `void Net::forward(std::vector<std::vector<Mat> >& outputBlobs, const std::vector<String>& outBlobNames)`


C++ example uses `net.forward(outs, getOutputsNames(net));`  https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L128
i.e. it uses this function `void Net::forward(std::vector<std::vector<Mat> >& outputBlobs, const std::vector<String>& outBlobNames)`

And it uses such functions to get Names of the output layers: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L269-L281

**Comment by leekwunfung817** [comment]
I know I should ask OpenCV, but I think @AlexeyAB  should understand the Exception

### This is the part of program, that you provide to me
I copy into my program then run, and got Exception

>             float scale = 1.0F / 255.0F;
>             Mat inputBlob = Dnn.blobFromImage(resized, scale, sz, new Scalar(0), false, false);
>             net.setInput(inputBlob, "data");
> 
>             System.out.println("Detect Classes: " + classes_names.length);
> 
>             java.util.List<Mat> result = new java.util.ArrayList<Mat>(2);
>             java.util.List<java.lang.String> outBlobNames = new java.util.ArrayList<java.lang.String>(2);
>             outBlobNames.add(0, "yolo_16");
>             outBlobNames.add(1, "yolo_23");
>             net.forward(result, outBlobNames);
> 
>             Mat result_1 = result.get(0);
>             Mat result_2 = result.get(1);
> 
>             for (Mat mat : result) {
>                 ExtractBeanFromMat(mat, im, frame, im_copy);
>             }

>             net.forward(result, outBlobNames);

I got the Exception
```
Detect Classes: 2

java.lang.Exception: unknown exception
	at org.opencv.dnn.Net.forward_4(Native Method)
	at org.opencv.dnn.Net.forward(Net.java:333)
	at InheritClass.ObjectDetectionHelper.detect(ObjectDetectionHelper.java:134)
	at DetectionCar.DetectCar.detect(DetectCar.java:26)
	at InheritClass.ObjectDetectionHelper.detect(ObjectDetectionHelper.java:94)
	at InheritClass.ObjectDetectionHelper.detect_directory(ObjectDetectionHelper.java:227)
	at DetectionCar.DetectCar.main(DetectCar.java:31)
```



### For dynamic yolo, I already implement this
>             float scale = 1.0F / 255.0F;
>             Mat inputBlob = Dnn.blobFromImage(resized, scale, sz, new Scalar(0), false, false);
>             net.setInput(inputBlob, "data");
>             
>             System.out.println("Detect Classes: " + classes_names.length);
>             java.util.List<java.lang.String> outBlobNames = new java.util.ArrayList<java.lang.String>(classes_names.length);
>             java.util.List<Mat> result = new java.util.ArrayList<Mat>(classes_names.length);
> 
>             List<String> layerNames = net.getLayerNames();
>             int count = 0;
>             for (String layerName : layerNames) {
>                 if (layerName.contains("yolo")) {
>                     System.out.println("Detect Layer " + layerName);
>                     outBlobNames.add(count, layerName);
>                     count++;
>                 }
>             }
> 
>             net.forward(result, outBlobNames);
>             for (Mat mat : result) {
>                 ExtractBeanFromMat(mat, im, frame, im_copy);
>             }
>             


>             net.forward(result, outBlobNames);
I got the Exception
```
Detect Classes: 2

java.lang.Exception: unknown exception
	at org.opencv.dnn.Net.forward_4(Native Method)
	at org.opencv.dnn.Net.forward(Net.java:333)
	at InheritClass.ObjectDetectionHelper.detect(ObjectDetectionHelper.java:134)
	at DetectionCar.DetectCar.detect(DetectCar.java:26)
	at InheritClass.ObjectDetectionHelper.detect(ObjectDetectionHelper.java:94)
	at InheritClass.ObjectDetectionHelper.detect_directory(ObjectDetectionHelper.java:227)
	at DetectionCar.DetectCar.main(DetectCar.java:31)
```

**Comment by leekwunfung817** [comment]
I have been ask in OpenCV
https://github.com/opencv/opencv/issues/12441#issue-357522261

**Comment by leekwunfung817** [comment]
I give up to use OpenCV-Yolo, I use Darknet-Yolo.
Because they are too different, I cannot use it.

**Comment by galdalali** [comment]
Did you find a solution for this issue?

I'm having the same issue with OpenCV 4.4.0 while runing object_detection.cpp sample with DNN_BACKEND_CUDA and DNN_TARGET_CUDA_FP16.
Tried to resize the image to the network input size but it doesn't seems to help.

I'm getting different results (a lot of false positive ones) comparing to darknet detector (good results) with the same weights and configuration.
