### ISSUE TITLE
darknet_video.py //error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

### ISSUE THREAD

**Issue by BahaaMansour** [AlexeyAB/darknet#2242]
-When i run my darknet_video.py it starts processing the video with 6 fps and after it finishes it outputs a video file "output.avi" that has only 6 kbs and cannot be opened because its corrupted. 
-When darknet_video.py finishes processing the video it gives this error. 
![image](https://user-images.githubusercontent.com/44228249/51352927-8180e400-1ac8-11e9-8771-36d3b896ac72.png)

**Comment by BahaaMansour** [comment]
I also want to know is there a way to increase the fps? i compiled the  yolo_cpp_dll.sln with GPU and CUDNN

**Comment by bit-scientist** [comment]
@BahaaMansour Hi,
Did you by any chance have any struggle to have your test video read by `cap = cv2.VideoCapture`? 
Although I am giving full path, trying with  `/` and `\` or their `//` or `\\`, putting `r` in front of full path, there is no success. 
```
Traceback (most recent call last):
  File "darknet_video.py", line 116, in <module>
    YOLO()
  File "darknet_video.py", line 98, in YOLO
    frame_rgb = cv2.cvtColor(frame_read, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor
```
In the code below, `print` outputs `None`, so it's surely not reading the frame at all. 
```
    while True:
        prev_time = time.time()
        ret, frame_read = cap.read()
        print("The value of frame is ", frame_read)
        frame_rgb = cv2.cvtColor(frame_read, cv2.COLOR_BGR2RGB)
```

What do you recommend?

**Comment by bit-scientist** [comment]
Hi, @BahaaMansour, it's nice to see you here.
I have a similar issue to your's. When I run **_darknet_video.cmd_**  command, network loads, outputs bunch of float numbers (outputs of `print(1/(time.time()-prev_time))` line in the file) and then stops abruptly with no error at all. There is **_output.avi_** file next **_darknet_video.cmd_**, it is not loaded as you said above. What did you do to solve this issue?
