### ISSUE TITLE
Deployment Requirements question

### ISSUE THREAD

**Issue by Christopheraburns** [AlexeyAB/darknet#2917]
I am hoping someone can clarify the deployment of a trained darknet model for me.

I trained a model on an AWS Ec2 P3 instance (running Ubuntu 18.04).  I compiled with LIBSO=1 to generate .SO files (it will only run on Linux hosts).  I also compiled with GPU to take advantage of the Ec2 instance V100's.

I tried unsuccessfully to run use the python (darknet.py) as well as call the .SO file from C++ code on a Linux VM running 16.04. 

My goal is to move this model to an Intel NUC that does not have a GPU

My question(s) are if I compile with GPU does that mean the final host of the model requires GPU or just the host it is trained on?

Am I able to just move the  .cfg, weights file and the .SO file to a random Linux host - that may not have GPU or a compiled version of Darknet - and make inferences?

TIA

**Comment by AlexeyAB** [comment]
@Christopheraburns Hi,

> I tried unsuccessfully to run use the python (darknet.py) as well as call the .SO file from C++ code on a Linux VM running 16.04.

What error did you get?

> My question(s) are if I compile with GPU does that mean the final host of the model requires GPU or just the host it is trained on?

You can train your model with `GPU=1 CUDNN=1 CUDNN_HALF=1`, and then use this model for Detection with `GPU=0 CUDNN=0 CUDNN_HALF=0`

> My goal is to move this model to an Intel NUC that does not have a GPU

So after that model is trained you can use it for detection on Intel NUC.
* Either by using this Darknet repo
* Or by using OpenCV-dnn module (without Darknet):
    * C++ example: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L192-L221
    * Python example: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py#L129-L150

Also you can connect NCS2 (Myriad X) to your Intel NUC by USB 3.0 (but I don't know will it be faster than just NUC): https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend


----

> Am I able to just move the .cfg, weights file and the .SO file to a random Linux host - that may not have GPU or a compiled version of Darknet - and make inferences?

Yes, you can, but you must compile `libdarknet.so` without GPU.
Or you should compile two different  `libdarknet.so` with differenat filenames: with and without GPU. And implement selecting apprepriate so-library in your code.

**Comment by Christopheraburns** [comment]
here is the error I receive when I moved my darknet .SO file to a linux host that did not have darknet compiled, or a GPU and tried to call via darknet.py  ( I did create a setup.py file and install the .SO with python bindings)
`
(base) chris@ubuntu:~/code/cardbot/YoloSetup$ python darknet.py
Traceback (most recent call last):
  File "darknet.py", line 67, in <module>
    lib = CDLL("libdarknet.so", RTLD_GLOBAL)
  File "/home/chris/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libdarknet.so: undefined symbol: _ZN2cv12resizeWindowERKNS_6StringEii
`

**Comment by AlexeyAB** [comment]
If you compiled Darknet with:
GPU=1 - then also you should copy CUDA libraries: libcuda.so, libcudart.so, libcublas.so, libcurand.so
CUDNN=1 - then also you should copy cuDNN libraries: libcudnn.so
OPENCV=1 - then also you should copy OpenCV libraries: libopencv_world.so
