### ISSUE TITLE
Using Windows DLL in Python

### ISSUE THREAD

**Issue by ds-motivo** [AlexeyAB/darknet#399]
I built a DLL per https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll

Then in the IDLE interpreter (to test) I loaded the DLL:
```
import os
from ctypes import *
lib = CDLL("yolo_cpp_dll.dll")
```
Then I tried to access the functions:
```
>>> lib.load_image("myimg.jpg")

Traceback (most recent call last):
  File "<pyshell#65>", line 1, in <module>
    lib.load_image("myimg.jpg")
  File "[scrubbed]\python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "[scrubbed]\python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'load_image' not found
```

So in a command prompt I looked up the function names built into the DLL and they look mangled:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>link.exe /dump /exports "[scrubbed]\python-test-dspc\yolo_cpp_dll.dll"
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file [scrubbed]\python-test-dspc\yolo_cpp_dll.dll

File Type: DLL

  Section contains the following exports for yolo_cpp_dll.dll

    00000000 characteristics
    5A8B6EAB time date stamp Mon Feb 19 16:41:15 2018
        0.00 version
           1 ordinal base
           9 number of functions
           9 number of names

    ordinal hint RVA      name

          1    0 00034E80 ??0Detector@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z
          2    1 000354B0 ??1Detector@@QEAA@XZ
          3    2 00035C50 ?detect@Detector@@QEAA?AV?$vector@Ubbox_t@@V?$allocator@Ubbox_t@@@std@@@std@@Uimage_t@@M_N@Z
          4    3 00035790 ?detect@Detector@@QEAA?AV?$vector@Ubbox_t@@V?$allocator@Ubbox_t@@@std@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@M_N@Z
          5    4 00035C30 ?free_image@Detector@@SAXUimage_t@@@Z
          6    5 00035780 ?get_net_height@Detector@@QEBAHXZ
          7    6 00035770 ?get_net_width@Detector@@QEBAHXZ
          8    7 00035B70 ?load_image@Detector@@SA?AUimage_t@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
          9    8 000361F0 ?tracking_id@Detector@@QEAA?AV?$vector@Ubbox_t@@V?$allocator@Ubbox_t@@@std@@@std@@V23@_NHH@Z

  Summary

        2000 .data
        1000 .gfids
        1000 .nvFatBi
       74000 .nv_fatb
        3000 .pdata
       11000 .rdata
        1000 .reloc
        1000 .rsrc
       41000 .text
        1000 _RDATA
```

So the function names are all crazy. Am I doing something wrong? I've already tried:
`Project -> Properties -> Linker -> Debugging -> Generate Debug Info = No`
and I've tried
`extern "C"` around the function declarations.

Anything else I can try?

**Comment by TomHJ** [comment]
is there any update? i got the same issue.

**Comment by AlexeyAB** [comment]
@TomHJ Now DLL/SO + darknet.py works fine on Python 2.x and 3.x on Windows/Linux:
* Linux: `darknet.py`
* Windows: `build/darknet/x64/darknet.py`
