### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by tinohager** [AlexeyAB/darknet#4614]
Hi Alexey

Currently i am working on .net core support for linux with your darknet lib. I try to build the `.so` file and make some tests. It already works when I pass a file path, but i have troubles with memory transfer i think the reason is the opencv library. I receive the `-1` https://github.com/AlexeyAB/darknet/blob/dcfeea30f195e0ca1210d580cac8b91b6beaf3f7/src/yolo_v2_class.cpp#L54 in my project. How i can check my `libdarknet.so` have opencv integrated?

My build process
```
docker pull ubuntu
docker run -it ubuntu /bin/bash
apt-get update && apt-get install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libopencv-dev -y
git clone https://github.com/AlexeyAB/darknet.git
cd darknet
sed -i 's/LIBSO=0/LIBSO=1/g' Makefile
sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
make
```

The output of my test
```
root@8ef05c292784:/test/bin/Debug/netcoreapp3.1# ./test
Yolo Test - Choose file:
Press enter to choose the default file car.jpg

Byte Transfer = 1, File Path = 2, default is 1

batch = 1, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  13 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  14 conv    125       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 125 0.043 BF
  15 detection
mask_scale: Using default '1.000000'
Total BFLOPS 6.977
Loading weights from yolov2-tiny-voc.weights...
 seen 32
Done! Loaded 16 layers from weights-file
Unhandled exception. System.NotImplementedException: C++ dll compiled incorrectly
   at Alturos.Yolo.YoloWrapper.Detect(Byte[] imageData)
   at test.Program.Main(String[] args) in /test/Program.cs:line 32
Aborted
root@8ef05c292784:/test/bin/Debug/netcoreapp3.1# ./test
Yolo Test - Choose file:
Press enter to choose the default file car.jpg

Byte Transfer = 1, File Path = 2, default is 1
2
batch = 1, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  13 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  14 conv    125       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 125 0.043 BF
  15 detection
mask_scale: Using default '1.000000'
Total BFLOPS 6.977
Loading weights from yolov2-tiny-voc.weights...
 seen 32
Done! Loaded 16 layers from weights-file
car
root@8ef05c292784:/test/bin/Debug/netcoreapp3.1#            
```

**Comment by AlexeyAB** [comment]
Hi Tino

You can do 
`make LIBSO=1 GPU=0 CUDNN=0 OPENCV=1 -j 8`
instead of
```
sed -i 's/LIBSO=0/LIBSO=1/g' Makefile
sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
make
```

----

> in my project. How i can check my libdarknet.so have opencv integrated?

1. Do you want function in the darknet.so that checks is it compiled with OPENCV=1?

2. May be better to implement conversion cv:Mat/... -> image_t in C# code instead of in C++-code of darknet.so libasry? and pass it to this function: https://github.com/AlexeyAB/darknet/blob/dcfeea30f195e0ca1210d580cac8b91b6beaf3f7/src/yolo_v2_class.cpp#L269
     or I can add another one function that takes `float *data, int w, int h, int c` instead of `image_t img`

**Comment by tinohager** [comment]
Hi AlexeyAB, the solution with [`image_t`](https://github.com/AlexeyAB/darknet/blob/cd1c7c32af3f40610aa8ed4c0a3d6ebfdd958460/include/yolo_v2_class.hpp#L31) sounds good for me. Did I understand correctly that the OpenCV library is not absolutely necessary for the in-memory transfer?

**Comment by AlexeyAB** [comment]
@tinohager 

>  Did I understand correctly that the OpenCV library is not absolutely necessary for the in-memory transfer?

Yes.

Darknet can be compiled as library darknet.so without OpenCV.

Ok I will add detect() for image_t

**Comment by tinohager** [comment]
Please give me a little more time I need to clarify a few points first
