### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by d3-worgan** [AlexeyAB/darknet#4869]
I am trying to use yolo in python. 

I have compiled the yolo_cpp_dll.dll and the yolo_cpp_dll_nogpu.dll. The dll's are in the same folder as the darknet.py script. But when I run the darknet.py script for GPU it says the specified module cannot be found? (The yolo_cpp_nogpu.dll works fine).

'''
Loading lib C:\darknet-master\build\darknet\x64\yolo_cpp_dll.dll
Traceback (most recent call last):
  File "c:/darknet-master/build/darknet/x64/darknet.py", line 133, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Anaconda\envs\object_detection\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
'''

I have tried copying 
cudnn64_7.dll
cudart64_100.dll
cublas64_100.dll
curand64_100.dll

opencv_ffmpeg340_64.dll
opencv_world340.dll

pthreadGC2.dll
pthreadVC2.dll

and 

vcruntime140.dll
msvcr100.dll
vcomp140.dll
msvcp140.dll

as suggested in this post https://github.com/AlexeyAB/darknet/issues/2306

Compiled with CUDA 10.0, everything is in C:\darknet-master\build\darknet\x64

Does anyone know if I have missed anything?

Thanks for help

**Comment by rockmosi** [comment]
i complied yolo_cpp_dll.dll and yolo_cpp.dll_nogpu.dll
it's not working. 
Do you have any progress?
