### ISSUE TITLE
How to read darknet object detector result in a python code

### ISSUE THREAD

**Issue by AkhilGKrishnan** [AlexeyAB/darknet#5190]
My project is written in python. so i need to connect my python script with darknet. When I give  `os.system("./darknet detector test data/obj.data cfg/yolov3.cfg backup/yolov3.weight sample.jpg")` command in python script, i need to get the output of the above detection my python program.. How to do this

**Comment by AkhilGKrishnan** [comment]
Hi @AlexeyAB 
Please help me

**Comment by AlexeyAB** [comment]
Compile Darknet as DLL/SO-library (use `LIBSO=1` in the Makefile)
and use these Python examples:
* https://github.com/AlexeyAB/darknet/blob/master/darknet.py
* https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

**Comment by shadmreese** [comment]
@AlexeyAB 
Could you provide an example command to use:

- https://github.com/AlexeyAB/darknet/blob/master/darknet.py
- https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

after Compile Darknet as DLL/SO-library?

Thanks

**Comment by mickkn** [comment]
Loading the DLL from the python gives me this error 

C:\darknet>python darknet_video.py
Traceback (most recent call last):
  File "darknet_video.py", line 8, in <module>
    import darknet
  File "C:\darknet\darknet.py", line 116, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Using Python 3.7.7
