### ISSUE TITLE
AttributeError: function 'network_width' not found, while executing darknet.py

### ISSUE THREAD

**Issue by vineeth0911** [AlexeyAB/darknet#5199]
I tried to execute "build\darknet\x64\darknet.py" after compiling both gpu & nogpu dll files and renamed them. 
I encountered the following error:

C:\darknet-master\build\darknet\x64>py darknet.py
Traceback (most recent call last):
  File "darknet.py", line 130, in <module>
    lib.network_width.argtypes = [c_void_p]
  File "C:\Users\CHEPURI VINEETH\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\CHEPURI VINEETH\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'network_width' not found

**Comment by vineeth0911** [comment]
please help me to resolve this issue .!
