### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by AlgorithmicIntelligence** [AlexeyAB/darknet#5223]
I use the same yolov3.cfg both on this repo and pjreddie repo(https://github.com/pjreddie/darknet), I got segmentation fault when the architecture of nn was initializing for this repo, but pjreddie worked well.

**Comment by Pidem** [comment]
same here

**Comment by taf2** [comment]
me too...
```
pi@raspberrypi:~/Desktop/darknet \> ./darknet detect cfg/yolov3.cfg yolov3.weights taf2-videos/out1.png
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128
    9 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
   10 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
   11 res    8                 152 x 152 x 128   ->   152 x 152 x 128
   12 conv    256  3 x 3 / 2   152 x 152 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   13 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   14 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   15 res   12                  76 x  76 x 256   ->    76 x  76 x 256
   16 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   17 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   18 res   15                  76 x  76 x 256   ->    76 x  76 x 256
   19 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   20 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   21 res   18                  76 x  76 x 256   ->    76 x  76 x 256
   22 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   23 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   24 res   21                  76 x  76 x 256   ->    76 x  76 x 256
   25 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   26 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   27 res   24                  76 x  76 x 256   ->    76 x  76 x 256
   28 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   29 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   30 res   27                  76 x  76 x 256   ->    76 x  76 x 256
   31 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   32 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   33 res   30                  76 x  76 x 256   ->    76 x  76 x 256
   34 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   35 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   36 res   33                  76 x  76 x 256   ->    76 x  76 x 256
   37 Segmentation fault
```

**Comment by taf2** [comment]
```
pi@raspberrypi:~/Desktop/darknet \> gdb ./darknet
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./darknet...done.
(gdb) run detect cfg/yolov3.cfg yolov3.weights taf2-videos/out1.png
Starting program: /home/pi/Desktop/darknet/darknet detect cfg/yolov3.cfg yolov3.weights taf2-videos/out1.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128
    9 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
   10 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
   11 res    8                 152 x 152 x 128   ->   152 x 152 x 128
   12 conv    256  3 x 3 / 2   152 x 152 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   13 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   14 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   15 res   12                  76 x  76 x 256   ->    76 x  76 x 256
   16 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   17 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   18 res   15                  76 x  76 x 256   ->    76 x  76 x 256
   19 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   20 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   21 res   18                  76 x  76 x 256   ->    76 x  76 x 256
   22 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   23 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   24 res   21                  76 x  76 x 256   ->    76 x  76 x 256
   25 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   26
Program received signal SIGSEGV, Segmentation fault.
0x000297a0 in make_convolutional_layer ()
(gdb) bt
#0  0x000297a0 in make_convolutional_layer ()
#1  0x0000004c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by taf2** [comment]
seems like this is a dup of #459

e.g. we're just running on machine with too little memory.

**Comment by AlexeyAB** [comment]
@taf2 

> 24 res   21                  76 x  76 x 256   ->    76 x  76 x 256
>    25 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
>    26
> Program received signal SIGSEGV, Segmentation fault.
> 0x000297a0 in make_convolutional_layer ()
> (gdb) bt
> #0  0x000297a0 in make_convolutional_layer ()
> #1  0x0000004c in ?? ()
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> (gdb)

You didn't use my repository.
Use this: https://github.com/AlexeyAB/darknet

**Comment by taf2** [comment]
anyways recompiling now with -g option to see if I can get more details...

**Comment by taf2** [comment]
```
pi@raspberrypi:~/Desktop/darknet \> gdb ./darknet
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./darknet...done.
(gdb) run detect cfg/yolov3.cfg yolov3.weights taf2-videos/out1.png
Starting program: /home/pi/Desktop/darknet/darknet detect cfg/yolov3.cfg yolov3.weights taf2-videos/out1.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128
    9 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
   10 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
   11 res    8                 152 x 152 x 128   ->   152 x 152 x 128
   12 conv    256  3 x 3 / 2   152 x 152 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   13 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   14 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   15 res   12                  76 x  76 x 256   ->    76 x  76 x 256
   16 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   17 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   18 res   15                  76 x  76 x 256   ->    76 x  76 x 256
   19 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   20 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   21 res   18                  76 x  76 x 256   ->    76 x  76 x 256
   22 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   23 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   24 res   21                  76 x  76 x 256   ->    76 x  76 x 256
   25 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   26
Program received signal SIGSEGV, Segmentation fault.
0x000297a0 in make_convolutional_layer (batch=76, batch@entry=0, h=0, h@entry=76, w=0, w@entry=76, c=c@entry=128, n=256,
    n@entry=7, groups=1, groups@entry=0, size=size@entry=3, stride=stride@entry=1, padding=padding@entry=1, activation=LEAKY,
    activation@entry=LOGISTIC, batch_normalize=batch_normalize@entry=1, binary=0, binary@entry=-1913190400, xnor=0, adam=0)
    at ./src/convolutional_layer.c:209
209	    for(i = 0; i < l.nweights; ++i) l.weights[i] = scale*rand_normal();
(gdb) bt
#0  0x000297a0 in make_convolutional_layer (batch=76, batch@entry=0, h=0, h@entry=76, w=0, w@entry=76, c=c@entry=128, n=256,
    n@entry=7, groups=1, groups@entry=0, size=size@entry=3, stride=stride@entry=1, padding=padding@entry=1, activation=LEAKY,
    activation@entry=LOGISTIC, batch_normalize=batch_normalize@entry=1, binary=0, binary@entry=-1913190400, xnor=0, adam=0)
    at ./src/convolutional_layer.c:209
#1  0x00055d20 in parse_convolutional (options=options@entry=0x518458, params=...) at ./src/parser.c:202
#2  0x0005838c in parse_network_cfg (filename=filename@entry=0xbefff578 "cfg/yolov3.cfg") at ./src/parser.c:777
#3  0x000525bc in load_network (cfg=cfg@entry=0xbefff578 "cfg/yolov3.cfg", weights=weights@entry=0xbefff587 "yolov3.weights",
    clear=clear@entry=0) at ./src/network.c:55
#4  0x00023fbc in test_detector (datacfg=<optimized out>, cfgfile=0xbefff578 "cfg/yolov3.cfg",
    weightfile=0xbefff587 "yolov3.weights", filename=filename@entry=0xbefff596 "taf2-videos/out1.png", thresh=thresh@entry=0.5,
    hier_thresh=hier_thresh@entry=0.5, outfile=outfile@entry=0x0, fullscreen=0) at ./examples/detector.c:569
#5  0x000117cc in main (argc=5, argv=0xbefff3d4) at ./examples/darknet.c:437
```

**Comment by taf2** [comment]
so issue with accessing memory for sure...

I would think this change makes sense to calculate the size of the buffer once and use l.nweights in the call to calloc but also - maybe doing a check to see if calloc returns NULL... maybe the extra branch is not needed since it'll just crash on low memory devices anyway...

```

diff --git a/src/convolutional_layer.c b/src/convolutional_layer.c
index 1fb58b0..5dc42bb 100644
--- a/src/convolutional_layer.c
+++ b/src/convolutional_layer.c
@@ -192,13 +192,13 @@ convolutional_layer make_convolutional_layer(int batch, int h, int w, int c, int
     l.pad = padding;
     l.batch_normalize = batch_normalize;

-    l.weights = calloc(c/groups*n*size*size, sizeof(float));
+    l.nweights = c/groups*n*size*size;
+    l.weights = calloc(l.nweights, sizeof(float));
     l.weight_updates = calloc(c/groups*n*size*size, sizeof(float));

     l.biases = calloc(n, sizeof(float));
     l.bias_updates = calloc(n, sizeof(float));

-    l.nweights = c/groups*n*size*size;
     l.nbiases = n;

     // float scale = 1./sqrt(size*size*c);

```
