### ISSUE TITLE
libgio-2.0.so.0: undefined symbol: g_ref_count_inc

### ISSUE THREAD

**Issue by harrymore** [AlexeyAB/darknet#5511]
hello, I  compiled the project as readme says, set LIBSO=1 in the Makefile and did make。
after that, ran
`./darknet detector test ./cfg/coco.data ./cfg/yolov4.cfg ./yolov4.weights ex.jpg`
and i got a predictions.jpg.
but when I ran 
`python darknet.py `
it raised an error:

> Traceback (most recent call last):
  File "darknet.py", line 129, in <module>
    lib = CDLL("/home/user1/darknet/libdarknet.so", RTLD_GLOBAL)
  File "/home/user1/anaconda3/envs/chineseocr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/user1/anaconda3/envs/chineseocr/bin/../lib/libgio-2.0.so.0: undefined symbol: g_ref_count_inc

and I found /home/user1/anaconda3/envs/chineseocr/bin/../lib/libgio-2.0.so.0 linked to libgio-2.0.so.0.6301.0,

but when I linked it to /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5600.4, it worked。
I doubt that libgio-2.0.so.0.6301.0 didn't work with libdarknet.so, is that so?

**Comment by sunmonk** [comment]
conda activate *****  then run python darknet.py
