### ISSUE TITLE
darknet_video.py does not work in windows 10 install. 

### ISSUE THREAD

**Issue by minertom** [AlexeyAB/darknet#6430]
I have run this code on my linux install and now I need to port it to Windows 10. The install works well, as in the command line I can run darknet commands and the results of inference are comparable to the results that I get on linux. My python code is different but this error even happens when I run the original python code that was posted two years ago.

Again, the error happens with the original 2 year old darknet_video.py file. The error should be easy to trace. I know that there is no libdarknet.so file but there is a dark.dll in the darknet-master directory. My guess is that the python code is just not invoking the dll.

Traceback (most recent call last):
  File "C:/darknet-master/darknet_video.py", line 115, in <module>
    YOLO()
  File "C:/darknet-master/darknet_video.py", line 58, in YOLO
    netMain = darknet.load_net_custom(configPath.encode(
AttributeError: module 'darknet' has no attribute 'load_net_custom'

Tnank You
Tom

**Comment by haviduck** [comment]
change libdarknet.so to darknet.dll or dark. dll depending on your repo. its in darknet.py
