### ISSUE TITLE
Jetson Nano Threading Problem

### ISSUE THREAD

**Issue by sarioglutalha** [AlexeyAB/darknet#6669]
When I try to run tiny model on Jetson Nano, I get an error the final error code does not exist.

Actually, the image freezes after it is displayed and when I terminate it, I see the following error message:

```
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
Since the final error is also missing, I could not find a solution.

**Comment by vfbsilva** [comment]
This message is because you killed the process, run it again and redirect output to a text file so you can check what is going on:
`./darknet blablablablablabla  > out_log.txt`
