### ISSUE TITLE
Pruning of yolov4.weights 

### ISSUE THREAD

**Issue by anusha657** [AlexeyAB/darknet#7123]
Hi ,
For my project I need to prune the yolov4.weights and after pruning the extension  (.weights ) should remain as it is.

**Comment by Hwijune** [comment]
hi! @anusha657 

Try applying the repo below. 

If there's a problem,

code should be modified to yolov4.

https://github.com/PengyiZhang/SlimYOLOv3

**Comment by anusha657** [comment]
@Hwijune - Thanks for your Response ,following the above suggested repository "https://github.com/PengyiZhang/SlimYOLOv3"  however I m stuck at one place

a ) I cloned https://github.com/ultralytics/yolov3

b) I m using yolov4.weights and yolov4.cfg from " !git clone https://github.com/AlexeyAB/darknet "

c) I m in step 1 - Normal Training
command used - python3 /content/yolov3/train.py --data /content/darknet/cfg/obj_coco.data --batch-size 16 -pt --weights /content/darknet/weights/yolov4.weights --cfg /content/darknet/cfg/yolov4.cfg

d)
Error occured : File "", line 1
python3 /content/yolov3/train.py --data /content/darknet/cfg/obj_coco.data --batch-size 16 -pt --weights /content/darknet/weights/yolov4.weights --cfg /content/darknet/cfg/yolov4.cfg
^
SyntaxError: invalid syntax

**Comment by Hwijune** [comment]
normal training(darknet) -> sparsity training(pytorch Slim yolov3) -> pruning -> darknet(last training) 

> @Hwijune - Thanks for your Response ,following the above suggested repository "https://github.com/PengyiZhang/SlimYOLOv3" however I m stuck at one place
> 
> a ) I cloned https://github.com/ultralytics/yolov3
> 
> b) I m using yolov4.weights and yolov4.cfg from " !git clone https://github.com/AlexeyAB/darknet "
> 
> c) I m in step 1 - Normal Training
> command used - python3 /content/yolov3/train.py --data /content/darknet/cfg/obj_coco.data --batch-size 16 -pt --weights /content/darknet/weights/yolov4.weights --cfg /content/darknet/cfg/yolov4.cfg
> 
> d)
> Error occured : File "", line 1
> python3 /content/yolov3/train.py --data /content/darknet/cfg/obj_coco.data --batch-size 16 -pt --weights /content/darknet/weights/yolov4.weights --cfg /content/darknet/cfg/yolov4.cfg
> ^
> SyntaxError: invalid syntax

@anusha657 

You don't have to do normal training again.

Follow the steps below.

normal training(darknet) -> sparsity training(pytorch Slim yolov3) -> pruning -> darknet(last training)

**Comment by anusha657** [comment]
Thanks @Hwijune for your response
I will not do normal training
Step 1 . I have darknet pre-trained weights (yolov4.weights)
Step2 .Sparsity training 
a)command as per repository -
 python yolov3/train_drone.py --cfg VisDrone2019/yolov3-spp3.cfg --data-cfg VisDrone2019/drone.data -sr --s 0.0001 --alpha 1.0
 here we dont have train_dron.py Therefore I will use train.py (of ulttalytics repo )
b) command that I will be using 

python yolov3/train.py --cfg yolov4.cfg --data-cfg coco.data -sr --s 0.0001 --alpha 1.0

Now here Y did we do normal training , where are the weights (yolov4.weights) in the command line of the sparsity training.

Clarity is missing as ideally output of the first step will be input to the second step.

**Comment by anusha657** [comment]
Above Issue is RESOLVED. Now currently stuck in another issue.
Step 1. I m doing the Sparsity Training Using the repository - https://github.com/PengyiZhang/SlimYOLOv3/ and went to Step 2.

Step 2. README.md
NOTICE:

TO run sparsity training and channel pruning, ultralytics/yolov3 is required.
We only provide the pruning method for channel pruning (prune.py) and subgradient method for sparsity training (sparsity.py).
Sparsity training can be done by using updateBN() in sparsity.py before optimizer.step() in train.py.
The channel pruning can be done by prune.py.

Step 3. Cloned the repository ultralytics/yolov3
Command Used - ! python3 /content/archived_yolov3/yolov3/train.py --cfg /content/darknet/cfg/yolov4.cfg --data /content/objcoco.data --weights /content/darknet/weights/yolov4.weights
[Error.txt](https://github.com/AlexeyAB/darknet/files/5710743/Error.txt)

**Comment by anusha657** [comment]
@Hwijune  Above issue is resolved now currently I am stuck in another issue.

Sparsity Training - for yolov4

command used -
! python3 /content/archived_yolov3/yolov3/train.py --cfg /content/darknet/cfg/yolov4.cfg --data /content/objcoco.data --weights /content/darknet/weights/yolov4.weights

Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='/content/darknet/cfg/yolov4.cfg', data='/content/objcoco.data', device='', epochs=300, evolve=False, freeze_layers=False, img_size=[320, 640], multi_scale=False, name='', nosave=False, notest=False, rect=False, resume=False, single_cls=False, weights='/content/darknet/weights/yolov4.weights')
Using CUDA device0 _CudaDeviceProperties(name='Tesla T4', total_memory=15079MB)

Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
2020-12-17 18:51:53.613694: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Model Summary: 327 layers, 6.43631e+07 parameters, 6.43631e+07 gradients
Optimizer groups: 110 .bias, 110 Conv2d.weight, 107 other
Reading image shapes: 0% 0/14 [00:00<?, ?it/s]Traceback (most recent call last):
File "/content/archived_yolov3/yolov3/utils/datasets.py", line 298, in init
with open(sp, 'r') as f: # read existing shapefile
FileNotFoundError: [Errno 2] No such file or directory: '/content/darknet/data/train_coco.shapes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/content/archived_yolov3/yolov3/train.py", line 432, in
train(hyp) # train normally
File "/content/archived_yolov3/yolov3/train.py", line 198, in train
single_cls=opt.single_cls)
File "/content/archived_yolov3/yolov3/utils/datasets.py", line 302, in init
s = [exif_size(Image.open(f)) for f in tqdm(self.img_files, desc='Reading image shapes')]
File "/content/archived_yolov3/yolov3/utils/datasets.py", line 302, in
s = [exif_size(Image.open(f)) for f in tqdm(self.img_files, desc='Reading image shapes')]
File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2809, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/obj/COCO_train2014_000000000009.jpg'
Reading image shapes: 0% 0/14 [00:00<?, ?it/s]

How can we resolve this issue ?

**Comment by Hwijune** [comment]
> @Hwijune Above issue is resolved now currently I am stuck in another issue.
> 
> Sparsity Training - for yolov4
> 
> command used -
> ! python3 /content/archived_yolov3/yolov3/train.py --cfg /content/darknet/cfg/yolov4.cfg --data /content/objcoco.data --weights /content/darknet/weights/yolov4.weights
> 
> Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
> Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='/content/darknet/cfg/yolov4.cfg', data='/content/objcoco.data', device='', epochs=300, evolve=False, freeze_layers=False, img_size=[320, 640], multi_scale=False, name='', nosave=False, notest=False, rect=False, resume=False, single_cls=False, weights='/content/darknet/weights/yolov4.weights')
> Using CUDA device0 _CudaDeviceProperties(name='Tesla T4', total_memory=15079MB)
> 
> Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
> 2020-12-17 18:51:53.613694: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
> Model Summary: 327 layers, 6.43631e+07 parameters, 6.43631e+07 gradients
> Optimizer groups: 110 .bias, 110 Conv2d.weight, 107 other
> Reading image shapes: 0% 0/14 [00:00<?, ?it/s]Traceback (most recent call last):
> File "/content/archived_yolov3/yolov3/utils/datasets.py", line 298, in init
> with open(sp, 'r') as f: # read existing shapefile
> FileNotFoundError: [Errno 2] No such file or directory: '/content/darknet/data/train_coco.shapes'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/content/archived_yolov3/yolov3/train.py", line 432, in
> train(hyp) # train normally
> File "/content/archived_yolov3/yolov3/train.py", line 198, in train
> single_cls=opt.single_cls)
> File "/content/archived_yolov3/yolov3/utils/datasets.py", line 302, in init
> s = [exif_size(Image.open(f)) for f in tqdm(self.img_files, desc='Reading image shapes')]
> File "/content/archived_yolov3/yolov3/utils/datasets.py", line 302, in
> s = [exif_size(Image.open(f)) for f in tqdm(self.img_files, desc='Reading image shapes')]
> File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2809, in open
> fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'data/obj/COCO_train2014_000000000009.jpg'
> Reading image shapes: 0% 0/14 [00:00<?, ?it/s]
> 
> How can we resolve this issue ?

Is there a coco data in the correct path?

https://github.com/zbyuan/pruning_yolov3 <- I think we should use repo here.

code is same

**Comment by anusha657** [comment]
Thanks @Hwijune for replying to the issue.

Is there a coco data in the correct path? ---yes

https://github.com/zbyuan/pruning_yolov3 <- I think we should use repo here. --------------------------------------is it compatible for yolov4 ?

**Comment by Hwijune** [comment]
> Thanks @Hwijune for replying to the issue.
> 
> Is there a coco data in the correct path? ---yes
> 
> https://github.com/zbyuan/pruning_yolov3 <- I think we should use repo here. --------------------------------------is it compatible for yolov4 ?

difference between yolov3 and yolov4 is 32 to 64.

you can modified simply

**Comment by dickyadrian** [comment]
Hi, did you have a solution to this problem yet? Would love to know more if you do succeed in optimizing YoloV4 models.

As for the code at https://github.com/ultralytics/yolov3, I notice that `train.py` doesn't include `-sr` flag for sparsity training and I think this would affect the training process
