### ISSUE TITLE
batch_detection_example() in darknet_images.py got error: OSError: exception: access violation reading 0x0000027ED2DA6040

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [AlexeyAB/darknet#7572]
@AlexeyAB Hi, I got this error when running the python file darknet_images.py with batch_detection_example(). 
Can you fix it? 

    * description of a bug: OSError: exception: access violation reading 0x0000027ED2DA6040 when run batch_detection_example in darknet_images.py
    * what command do you use? python darknet_images.py 
    with small changed as bellow:
  ```
if __name__ == "__main__":
    # unconmment next line for an example of batch processing
    batch_detection_example()
    # main()
```
    * do you use Win/Linux/Mac? -> Windows

```
python darknet_images.py

  Try to load weights: yolov4.weights 
Loading weights from yolov4.weights...
 seen 64, trained: 32032 K-images (500 Kilo-batches_64)
Done! Loaded 162 layers from weights-file 
Loaded - names_list: data/coco.names, classes = 80 
 
  File "\x64\darknet_images.py", line 234, in <module>
    batch_detection_example()
  File "t\x64\darknet_images.py", line 187, in batch_detection_example
    class_colors, batch_size=batch_size)
  File "\x64\darknet_images.py", line 124, in batch_detection
    image_height, thresh, hier_thresh, None, 0, 0)
OSError: exception: access violation reading 0x0000027ED2DA6040
```

**Comment by jackneil** [comment]
Same issue. Any help appreciated! 
Thanks

**Comment by Bubble-water** [comment]
i have same error.
how to fix error?

**Comment by longxiaohai** [comment]
I have same error, how to fix it?

**Comment by kent1201** [comment]
Same Issue.
I'm using CUDA11.2, visual studio 2019.

Here is my error message:

Traceback (most recent call last):
  File "darknet_images.py", line 237, in <module>
    batch_detection_example()
  File "darknet_images.py", line 190, in batch_detection_example
    class_colors, batch_size=args.batch_size)
  File "darknet_images.py", line 125, in batch_detection
    image_height, thresh, hier_thresh, None, 0, 0)
OSError: exception: access violation reading 0x00000195C91E1040
