### ISSUE TITLE
Need to generate loss curve in Excel from nohup output

### ISSUE THREAD

**Issue by ashuezy** [AlexeyAB/darknet#777]
Hi,

I am training the model with -dont_show parameter on the centos server with nohup command. Since i don't have the GUI screen available can i use the nohup output to generate the same in Excel Chart later on ? If yes then which of the following values do i need from the output:

3336: 0.108272, 0.274845 avg, 0.001000 rate, 4.562884 seconds, 213504 images
Loaded: 0.000040 seconds
Region 82 Avg IOU: 0.530140, Class: 0.213033, Obj: 0.001408, No Obj: 0.000057, .5R: 1.000000, .75R: 0.000000,  count: 1
Region 94 Avg IOU: 0.437775, Class: 0.426487, Obj: 0.000276, No Obj: 0.000024, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .75R: -nan,  count: 0
 
Thanks.

**Comment by Adesun** [comment]
you can have a try [log_parser](https://github.com/AlexeyAB/darknet/tree/master/scripts/log_parser).

**Comment by ashuezy** [comment]
Errors

parsing 3400/3469
Traceback (most recent call last):
  File "log_parser.py", line 107, in <module>
    log_parser(args)
  File "log_parser.py", line 98, in log_parser
    plt.savefig(save_path, dpi=300)
  File "E:\Python36\lib\site-packages\matplotlib\pyplot.py", line 710, in savefig
    res = fig.savefig(*args, **kwargs)
  File "E:\Python36\lib\site-packages\matplotlib\figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "E:\Python36\lib\site-packages\matplotlib\backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "E:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 513, in print_png
    FigureCanvasAgg.draw(self)
  File "E:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "E:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "E:\Python36\lib\site-packages\matplotlib\figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "E:\Python36\lib\site-packages\matplotlib\image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "E:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "E:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "E:\Python36\lib\site-packages\matplotlib\image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "E:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "E:\Python36\lib\site-packages\matplotlib\axis.py", line 1190, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "E:\Python36\lib\site-packages\matplotlib\axis.py", line 1028, in _update_ticks
    tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
  File "E:\Python36\lib\site-packages\matplotlib\axis.py", line 971, in iter_ticks
    majorLocs = self.major.locator()
  File "E:\Python36\lib\site-packages\matplotlib\ticker.py", line 1743, in __call__
    return self.tick_values(vmin, vmax)
  File "E:\Python36\lib\site-packages\matplotlib\ticker.py", line 1752, in tick_values
    return self.raise_if_exceeds(locs)
  File "E:\Python36\lib\site-packages\matplotlib\ticker.py", line 1463, in raise_if_exceeds
    len(locs), locs[0], locs[-1]))
RuntimeError: Locator attempting to generate 1024 ticks from -47.0 to 976.0: exceeds Locator.MAXTICKS

**Comment by Adesun** [comment]
@ashuezy 
I could find the problem and fix it,  if  you would like to share your training log  for test.

**Comment by ashuezy** [comment]
@Adesun 
I was getting the exception because of negative values in my training format.

**Comment by RyanCV** [comment]
@ashuezy I got the samilar error 
` RuntimeError: Locator attempting to generate 1757 ticks from -70.0 to 1686.0: exceeds Locator.MAXTICKS`
Did u know how to solve it?

**Comment by Adesun** [comment]
@ashuezy @RyanCV 
pls try new code pushed.
