### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by cespedesk** [AlexeyAB/darknet#8195]
I have been using this code for months and now is giving me this problem.
All other codes from the api works fine, picture,video and webcam examples work fine.
But this stopped working. Please help me out.

import cv2 as cv
import numpy as np

cap = cv.VideoCapture(0)
whT = 320
confThreshold =0.5
nmsThreshold= 0.2

## Coco Names
classesFile = "/media/kc/4T/4T-Repos/darknet/data/coco.names"
classNames = []
with open(classesFile, 'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')
#print(classNames)
## Model Files
modelConfiguration = "/media/kc/4T/4T-Repos/darknet/cfg/yolov4.cfg"
modelWeights = "/media/kc/4T/4T-Repos/darknet/yolov4.weights"
net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)

def findObjects(outputs,img):
    hT, wT, cT = img.shape
    bbox = []
    classIds = []
    confs = []
    for output in outputs:
        for det in output:
            scores = det[5:]
            classId = np.argmax(scores)
            confidence = scores[classId]
            if confidence > confThreshold:
                w,h = int(det[2]*wT) , int(det[3]*hT)
                x,y = int((det[0]*wT)-w/2) , int((det[1]*hT)-h/2)
                bbox.append([x,y,w,h])
                classIds.append(classId)
                confs.append(float(confidence))

    indices = cv.dnn.NMSBoxes(bbox, confs, confThreshold, nmsThreshold)
    print(indices,classIds)

    for i in indices:
        i = i[0]
        box = bbox[i]
        x, y, w, h = box[0], box[1], box[2], box[3]
        print(x,y,w,h)
        cv.rectangle(img, (x, y), (x+w,y+h), (255, 0 , 255), 2)
        cv.putText(img,f'{classNames[classIds[i]].upper()} {int(confs[i]*100)}%',
                  (x, y-10), cv.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 255), 2)

while True:
    success, img = cap.read()
    blob = cv.dnn.blobFromImage(img, 1 / 255, (whT, whT), [0, 0, 0], 1, crop=False)
    net.setInput(blob)
    layersNames = net.getLayerNames()
    outputNames = [(layersNames[i[0] - 1]) for i in net.getUnconnectedOutLayers()]
    outputs = net.forward(outputNames)
    findObjects(outputs,img)
    cv.imshow('Image', img)
    #cv.waitKey(1)

Traceback (most recent call last):
  File "/media/kc/4T/4T-Repos/darknet/turet.py", line 57, in <module>
    outputNames = [(layersNames[i[0] - 1]) for i in net.getUnconnectedOutLayers()]
  File "/media/kc/4T/4T-Repos/darknet/turet.py", line 57, in <listcomp>
    outputNames = [(layersNames[i[0] - 1]) for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
    #print(x)

**Comment by halvomez** [comment]
`lnames = [lnames[i - 1] for i in net.getUnconnectedOutLayers()]` 
for opencv 4.5.4.58 or
`lnames = [lnames[i[0] - 1] for i in np.reshape(net.getUnconnectedOutLayers(), (3, 1))]`
for backward compability

**Comment by cespedesk** [comment]
Thanks very helpful. So saved my project. 👏👏👏

**Comment by cespedesk** [comment]
I am ruing the code like this now, but it is failing at  i = i[0]. If I comet out the 'for' loop it runs but is not printing the list of classes neither.

import cv2 as cv
import numpy as np


cap = cv.VideoCapture(0)
whT = 320
confThreshold =0.5
nmsThreshold= 0.2

#### LOAD MODEL
## Coco Names
classesFile = "/media/kc/4T/4T-Repos/darknet/data/coco.names"
classNames = []
with open(classesFile, 'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')
#print(classNames)
## Model Files
modelConfiguration = "/media/kc/4T/4T-Repos/darknet/cfg/yolov4.cfg"
modelWeights = "/media/kc/4T/4T-Repos/darknet/yolov4.weights"
net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)


while True:
    success, img = cap.read()
    blob = cv.dnn.blobFromImage(img, 1 / 255, (whT, whT), [0, 0, 0], 1, crop=False)
    net.setInput(blob)
    layersNames = net.getLayerNames()
    outputNames = [(layersNames[i[0] - 1]) for i in np.reshape(net.getUnconnectedOutLayers(), (3, 1))]
    outputs = net.forward(outputNames)

    hT, wT, cT = img.shape
    bbox = []
    classIds = []
    confs = []
    for output in outputs:
        for det in output:
            scores = det[5:]
            classId = np.argmax(scores)
            confidence = scores[classId]
            if confidence > confThreshold:
                w,h = int(det[2]*wT) , int(det[3]*hT)
                x,y = int((det[0]*wT)-w/2) , int((det[1]*hT)-h/2)
                bbox.append([x,y,w,h])
                classIds.append(classId)
                confs.append(float(confidence))

    indices = cv.dnn.NMSBoxes(bbox, confs, confThreshold, nmsThreshold)
    print(indices,classIds)

    for i in indices:
        i = i[0]
        box = bbox[i]
        x, y, w, h = box[0], box[1], box[2], box[3]
        print(x,y,w,h)
        cv.rectangle(img, (x, y), (x+w,y+h), (255, 0 , 255), 2)
        cv.putText(img,f'{classNames[classIds[i]].upper()} {int(confs[i]*100)}%',
                  (x, y-10), cv.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 255), 2)
        cv.imshow('Image', img)
    #cv.waitKey(1)
    #print(x)

() []
() []
() []
() []
() []
() []
() []
[1] [56, 56]
Traceback (most recent call last):
  File "/media/kc/4T/4T-Repos/darknet/webcam.py", line 53, in <module>
    i = i[0]
IndexError: invalid index to scalar variable.
