### ISSUE TITLE
darknet.py: FileNotFoundError: Could not find module 'darknet.dll'. Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by Kami0n** [AlexeyAB/darknet#8275]
When I try to run darknet.py on windows, I get:
```
> python darknet.py
Traceback (most recent call last):
  File "darknet.py", line 241, in <module>
    lib = CDLL("darknet.dll", RTLD_GLOBAL)
  File "C:\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'darknet.dll'. Try using the full path with constructor syntax.
```

**Comment by m-kalashnikova** [comment]
I have the same issue too
is there any chance to get some feedback about that?

**Comment by DavraYoung** [comment]
same with me
Windows 11. I used VCpkg to build

**Comment by Fugashu** [comment]
Same problem here.
Also used W11 VCpkg

**Comment by Fugashu** [comment]
Solved it:
I ran dependency walker and found that there were a few dlls actually missing, which i then copied from the root dir to my build directory. The issue is not really the darknet.dll, but the dlls it depends on.

**Comment by DavraYoung** [comment]
I solved it, by downgrading my python to 3.7. Turns out new python versions behave differently
